//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopeyesRolesMod.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PopeyesRolesMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a shield to protect a [8DFFFFFF]Crewmate[] ähnelt.
        /// </summary>
        internal static string DetectiveImpostorText {
            get {
                return ResourceManager.GetString("DetectiveImpostorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detective Options ähnelt.
        /// </summary>
        internal static string DetectiveOptions {
            get {
                return ResourceManager.GetString("DetectiveOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detective ähnelt.
        /// </summary>
        internal static string DetectiveRoleName {
            get {
                return ResourceManager.GetString("DetectiveRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maintain important systems on the ship ähnelt.
        /// </summary>
        internal static string EngineerImpostorText {
            get {
                return ResourceManager.GetString("EngineerImpostorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engineer Options ähnelt.
        /// </summary>
        internal static string EngineerOptions {
            get {
                return ResourceManager.GetString("EngineerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engineer ähnelt.
        /// </summary>
        internal static string EngineerRoleName {
            get {
                return ResourceManager.GetString("EngineerRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shoot the [FF0000FF]Impostor[] ähnelt.
        /// </summary>
        internal static string HunterImpostorText {
            get {
                return ResourceManager.GetString("HunterImpostorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kill Cooldown ähnelt.
        /// </summary>
        internal static string HunterKillCooldown {
            get {
                return ResourceManager.GetString("HunterKillCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hunter Options ähnelt.
        /// </summary>
        internal static string HunterOptions {
            get {
                return ResourceManager.GetString("HunterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hunter ähnelt.
        /// </summary>
        internal static string HunterRoleName {
            get {
                return ResourceManager.GetString("HunterRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [D09BD9FF]Fake Tasks
        ///[D09BD9FF]Get Voted Out ähnelt.
        /// </summary>
        internal static string JesterFakeTasks {
            get {
                return ResourceManager.GetString("JesterFakeTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get voted off of the ship to win ähnelt.
        /// </summary>
        internal static string JesterImpostorText {
            get {
                return ResourceManager.GetString("JesterImpostorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jester Options ähnelt.
        /// </summary>
        internal static string JesterOptions {
            get {
                return ResourceManager.GetString("JesterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jester ähnelt.
        /// </summary>
        internal static string JesterRoleName {
            get {
                return ResourceManager.GetString("JesterRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] popeyes_roles_mod {
            get {
                object obj = ResourceManager.GetObject("popeyes_roles_mod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Morph Cooldown ähnelt.
        /// </summary>
        internal static string ShapeShifterMorphCooldown {
            get {
                return ResourceManager.GetString("ShapeShifterMorphCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Morph Duration ähnelt.
        /// </summary>
        internal static string ShapeShifterMorphDuration {
            get {
                return ResourceManager.GetString("ShapeShifterMorphDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shape Shifter Options ähnelt.
        /// </summary>
        internal static string ShapeShifterOptions {
            get {
                return ResourceManager.GetString("ShapeShifterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shape Shifter ähnelt.
        /// </summary>
        internal static string ShapeShifterRoleName {
            get {
                return ResourceManager.GetString("ShapeShifterRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample Cooldown ähnelt.
        /// </summary>
        internal static string ShapeShifterSampleCooldown {
            get {
                return ResourceManager.GetString("ShapeShifterSampleCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shielded Player Sees Shield ähnelt.
        /// </summary>
        internal static string ShieldedPlayerSeesShield {
            get {
                return ResourceManager.GetString("ShieldedPlayerSeesShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spawn Chance ähnelt.
        /// </summary>
        internal static string SpawnChance {
            get {
                return ResourceManager.GetString("SpawnChance", resourceCulture);
            }
        }
    }
}
